name: qbk_simple_app
description: QBK Aplicacion simple sin 3D

version: 13.0.0+13

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  table_calendar: ^2.2.3
  keyboard_avoider: ^0.1.2
  boardview: ^0.2.2

  firebase_core: ^1.7.0
  cloud_firestore: ^2.5.3
  cloud_firestore_web: ^2.4.3
  firebase_auth: ^3.1.3
  firebase_auth_web: ^3.1.2

  modal_progress_hud: ^0.1.3
  firebase_database: ^8.0.0
  provider: ^6.0.1

  flutter_spinkit: ^5.1.0
  intl: ^0.17.0
  reorderables: ^0.4.0
  connectivity: ^3.0.6
  email_validator: ^2.0.1
  responsive_builder: ^0.4.1
  firebase_messaging: ^10.0.8
  google_sign_in: ^5.1.0
  share: ^2.0.4
  random_string: ^2.1.0

  googleapis: ^5.0.1
  googleapis_auth: ^1.1.0
  # url_launcher: ^6.0.12
  http_parser: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: BioRhyme
      fonts:
        - asset: fonts/BioRhyme/BioRhyme-Bold.ttf
        - asset: fonts/BioRhyme/BioRhyme-ExtraBold.ttf
        - asset: fonts/BioRhyme/BioRhyme-ExtraLight.ttf
        - asset: fonts/BioRhyme/BioRhyme-Regular.ttf

analyzer:
  enable-experiment:
    -spread-collectoins